apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bl-back-core
  description: Servicio core de funcionalidades BLUP
  tags:
    - java
    - spring
spec:
  type: service
  lifecycle: production
  owner: blup-team
  definition: |
    openapi: 3.0.0
    info:
      title: Service API
      version: 1.0.0
    paths:
      /actuator/health:
        get:
          summary: Health check
          responses:
            '200':
              description: UP
